import { Token, TokenId } from "./types";

export const TOKENS: { [key in TokenId]: Token } = {
  [TokenId.BTC]: {
    id: TokenId.BTC,
    icon: "/tokens/bitcoin.svg",
    symbol: "BTC",
    name: "Bitcoin",
    address: "",
  },
  [TokenId.OP]: {
    id: TokenId.OP,
    icon: "/tokens/optimism.svg",
    symbol: "OP",
    name: "Optimism",
    address: "",
  },
  [TokenId.USDC]: {
    id: TokenId.USDC,
    icon: "/tokens/usd-coin-usdc.svg",
    symbol: "USDC",
    name: "USDC",
    address: "0xe05606174bac4A6364B31bd0eCA4bf4dD368f8C6",
  },
  [TokenId.ETH]: {
    id: TokenId.ETH,
    icon: "/tokens/eth-mainnet.svg",
    symbol: "ETH",
    name: "Ethereum",
    address: "0x5D571ACfeB273bE53eDc2C55A1D7BCB8E6Cfbc81",
  },
  [TokenId.MATIC]: {
    id: TokenId.MATIC,
    icon: "/tokens/polygon-matic.svg",
    symbol: "MATIC",
    name: "Matic",
    address: "",
  },
  [TokenId.AVAX]: {
    id: TokenId.AVAX,
    icon: "/tokens/avalanche.svg",
    symbol: "AVAX",
    name: "Avalanche",
    address: "",
  },
  [TokenId.FTM]: {
    id: TokenId.FTM,
    icon: "/tokens/fantom.svg",
    symbol: "FTM",
    name: "Fantom",
    address: "",
  },
  [TokenId.MOVR]: {
    id: TokenId.MOVR,
    icon: "/tokens/movr.svg",
    symbol: "MOVR",
    name: "Moonriver",
    address: "",
  },
  [TokenId.DOT]: {
    id: TokenId.DOT,
    icon: "/tokens/polkadot.svg",
    symbol: "DOT",
    name: "Pokadot",
    address: "",
  },
  [TokenId.PICA]: {
    id: TokenId.PICA,
    icon: "/tokens/picasso.svg",
    symbol: "PICA",
    name: "Picasso",
    address: "",
  },
  [TokenId.KSM]: {
    id: TokenId.KSM,
    icon: "/tokens/dotsama-kusama.svg",
    symbol: "KSM",
    name: "Kusama",
    address: "",
  },
  [TokenId.CHAOS]: {
    id: TokenId.CHAOS,
    icon: "/tokens/chaos.svg",
    symbol: "CHAOS",
    name: "Chaos",
    address: "",
  },
  [TokenId.SOL]: {
    id: TokenId.SOL,
    icon: "/tokens/solana.svg",
    symbol: "SOL",
    name: "Solana",
    address: "",
  },
};
