name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Deploy - DEV
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          yarn install --immutable
          yarn vercel --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy - PROD
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          yarn install --immutable
          yarn vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
